DBConfig:
  MongoURI: mongodb://localhost:27017
SearchEngineConfig:
  # RussianStopWordsPath: /app/pkg/parser/utils/russian_stop_words.txt
  # EnglishStopWordsPath: /app/pkg/parser/utils/english_stop_words.txt
  RussianStopWordsPath: ../pkg/parser/utils/russian_stop_words.txt
  EnglishStopWordsPath: ../pkg/parser/utils/english_stop_words.txt
  Port: 8080
