version: '3.8'

services:
  mongo:
    image: mongo:4.4 # 5 версия не работает на маке....
    container_name: my-mongo
    ports:
      - "27017:27017"
    
  app:
    build: .
    container_name: Search-Engine
    environment:
      - MONGO_URI=mongodb://my-mongo:27017/InvertIndex
      - LOCAL_MONGO_URI=mongodb://localhost:27017
      - RUSSIAN_STOP_WORDS_PATH=/app/pkg/parser/utils/russian_stop_words.txt
      - ENGLISH_STOP_WORDS_PATH=/app/pkg/parser/utils/english_stop_words.txt
    volumes:
      - ./file.txt:/app/test_file_1.txt
      - ./pkg/parser/utils/english_stop_words.txt:/app/pkg/parser/utils/english_stop_words.txt
      - ./pkg/parser/utils/russian_stop_words.txt:/app/pkg/parser/utils/russian_stop_words.txt
    depends_on:
      - mongo
