name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - GitHub_actions
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build, test and deploy
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: tests
      #   run: |
      #     ./go_tests.go

      - name: Build binary
        run: |
          go build -o search-engine .

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/search-engine:${{ github.sha }} .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/search-engine:${{ github.sha }}
