name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - GitHub_actions
      - Frontend
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build, test and deploy
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: tests
      #   run: |
      #     ./go_tests.go

      - name: Build binary
        run: |
          go build -o search-engine .

      - name: Build Docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/search-engine:${{ github.sha }} .
      - name: Log in to Docker Hub
        run: sudo echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker image
        run: |
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/search-engine:${{ github.sha }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies and build Vue app
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist


      - name: Start Docker Compose
        run: sudo docker-compose up -d
